name: 'Setup k3d'
description: 'GitHub Action for setting up k3d'
author: 'rinx <rintaro.okamura@gmail.com>'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  version:
    description: 'k3d version'
    required: false
    default: 'latest'
  name:
    description: 'cluster name'
    required: false
    default: 'mycluster'
  skipClusterCreation:
    description: 'if "true", the action will not create a cluster, just acquire the tools'
    required: false
    default: 'false'
  ingressPort:
    description: 'if it is not "0", ingress will be exposed to the specified port'
    required: false
    default: '0'
  agents:
    description: 'number of agents'
    required: false
    default: '0'
  options:
    description: 'options for k3d cluster create command'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.name }}
    - ${{ inputs.skipClusterCreation }}
    - ${{ inputs.ingressPort }}
    - ${{ inputs.agents }}
    - ${{ inputs.options }}
